In [17]:
import numpy as np
import pandas as pd
import os
import nltk
from nltk.stem import WordNetLemmatizer

## Load

In [2]:
out_path = '../tbip/data/covid-tweets-2020/raw/covid_tweets.csv'
base_path = 'tweets/'

ls = []
for path, directory, file in os.walk(base_path):
    for name in sorted(file):
        if name.endswith('.csv'):
            filename = os.path.join(path, name)
            df = pd.read_csv(filename, header=0, index_col=None, engine='python')
            ls.append(df)

tweets = pd.concat(ls, axis=0, ignore_index=True)
print(len(tweets))
# tweets.to_csv(out_path)

1395217

In [3]:
tweets.head()

,id,tweet,time,description
0,1219751790654185473,RT @NFIDvaccines: #Pregnant? Learn tips for ha...,2020-01-21 22:41:03,"We work to improve the health of women, childr..."
1,1219767818863902722,RT @grandsupremnews: CDC CONFIRMED IT EXPECTS ...,2020-01-21 23:44:44,“Promoting Positive Disabilty Awareness” Words...
2,1219764042278944768,First Case of Mystery Coronavirus Found In Was...,2020-01-21 23:29:44,#ARMY #SFC #ENGINEER #VETERAN 21H4H 21B 21C 21...
3,1219782244388298753,RT @nytimes: Breaking News: The first U.S. cas...,2020-01-22 00:42:04,NaN
4,1219797234029494272,RT @nytimes: Breaking News: The first U.S. cas...,2020-01-22 01:41:37,NaN

## Preprocess

In [4]:
# drop NaNs
tweets = tweets.dropna(subset=['description', 'tweet'])
# remove Retweeted content
tweets = tweets.drop(tweets[tweets.tweet.str.startswith('RT')].index)
print(len(tweets))

def preprocess(tweet):
    parsed = nltk.word_tokenize(tweet)

301621

In [5]:
lemmatizer = WordNetLemmatizer()

academic_kw = set(['prof', 'professor' 'lecture', 'lecturer' 'university', 'school', 'department', 'edu', 'researcher', 'doctorate',
              'faculty', 'academic', 'college', 'post', 'doctoral', 'phd', 'ph.d', 'dphil', 'teacher',
              'conference', 'staff', 'teaching', 'academy', 'taught', 'academical', 'scholar'])
academic_kw = set([lemmatizer.lemmatize(w) for w in academic_kw])

journalist_kw = set(['digital', 'media', 'multimedia', 'journal', 'journalist', 'news', 'journalism', 'digital',
                 'reporter', 'writer', 'reporting', 'editor', 'newspaper', 'blogger', 'columnist', 
                'correspondent', 'press', 'writing'])
journalist_kw = set([lemmatizer.lemmatize(w) for w in journalist_kw])

doctors_ls = 'physician vet surgeon medicine medico doc doctor md veterinarian gastroenterologist allergist dr. medical patient neurologist neuro neuroscientist neuroscience pediatrician medication clinic hospital gp specialist veterinary practitioner practitioner surgeon sophisticate dermatologist oncologist obstetrician medic clinician cardiologist internist nephrologist gynecologist radiologist nurse care dentist therapist pharmacist psychologist doctoral pathologist dr healer doctorate theologian radiotherapy neuropsychologist medician biomedicine geriatrician virologist disease virus oncology psychotic clinical placebo gastroenterology dermatology pseudomedical biomedical biomed'
doctors_kw = set(doctors_ls.split(' '))
doctors_kw = set([lemmatizer.lemmatize(w) for w in doctors_kw])

politicians_ls = 'minister mp leader party parliament house representative decocrat commons lords politics leader governor democrat candidate legislator demagogue campaigner statesman politico senator socialist republican political leader political presidency technocrat labourite democratic lawmaker jurist parliamentarian journalist servant reformer nationalist congressman populist activist diplomat stateswoman federalist communist liberal conservative labour wing member politically president tory government served presidential advocate industrialist minister governmental parliamentary deputy'
politicians_kw = set(politicians_ls.split(' '))
politicians_kw = set([lemmatizer.lemmatize(w) for w in politicians_kw])

In [6]:
tweets['description'] = tweets.description.apply(lambda x: nltk.word_tokenize(x))
tweets['description'] = tweets.description.apply(lambda x: [w.lower() for w in x])
tweets['description'] = tweets.description.apply(lambda x: [lemmatizer.lemmatize(w) for w in x])

In [7]:
tweets.head()

,id,tweet,time,description
2,1219764042278944768,First Case of Mystery Coronavirus Found In Was...,2020-01-21 23:29:44,"[#, army, #, sfc, #, engineer, #, veteran, 21h..."
9,1219844392745422848,Killer Chinese virus has been reported in the ...,2020-01-22 04:49:01,"[i, am, a, realtor, with, agner, &, associate,..."
16,1219905081681829888,"Hey, @CDCFlu and other CDC accounts! How come ...",2020-01-22 08:50:10,"[love, .net, ,, software, development, ,, know..."
19,1219918349431377921,@realDonaldTrump @Davos First transferred case...,2020-01-22 09:42:54,"[entertainer/food, enthusiast/engaged, housesp..."
21,1219912177089314817,Coronavirus animation awaiting approval. 3 sec...,2020-01-22 09:18:22,"[i, 'm, an, after, effect, ,, cinema4d, and, x..."

In [8]:
tweets['academic_count'] = tweets.description.apply(lambda x: len([w for w in x if w in academic_kw]))
tweets['journalist_count'] = tweets.description.apply(lambda x: len([w for w in x if w in journalist_kw]))
tweets['doctor_count'] = tweets.description.apply(lambda x: len([w for w in x if w in doctors_kw]))
tweets['politician_count'] = tweets.description.apply(lambda x: len([w for w in x if w in politicians_kw]))

In [9]:
tweets.head(10)

,id,tweet,time,description,academic_count,journalist_count,doctor_count,politician_count
2,1219764042278944768,First Case of Mystery Coronavirus Found In Was...,2020-01-21 23:29:44,"[#, army, #, sfc, #, engineer, #, veteran, 21h...",0,0,0,0
9,1219844392745422848,Killer Chinese virus has been reported in the ...,2020-01-22 04:49:01,"[i, am, a, realtor, with, agner, &, associate,...",0,0,0,0
16,1219905081681829888,"Hey, @CDCFlu and other CDC accounts! How come ...",2020-01-22 08:50:10,"[love, .net, ,, software, development, ,, know...",0,0,0,0
19,1219918349431377921,@realDonaldTrump @Davos First transferred case...,2020-01-22 09:42:54,"[entertainer/food, enthusiast/engaged, housesp...",0,0,0,1
21,1219912177089314817,Coronavirus animation awaiting approval. 3 sec...,2020-01-22 09:18:22,"[i, 'm, an, after, effect, ,, cinema4d, and, x...",0,0,0,0
26,1219929776665718784,Because of #China ‘s lack of hygiene and moral...,2020-01-22 10:28:18,"[#, 手足互科, #, 5demandsnot1less, #, standwithhon...",0,0,0,0
30,1219930852341186560,This terrifying graph shows how fast the Wuhan...,2020-01-22 10:32:35,"[what, you, want, to, know, about, science, .,...",0,0,0,0
34,1219950813486837760,If the world🌐 is somehow dominant by #CCPChina...,2020-01-22 11:51:54,"[自由無價, 五大訴求, 缺一不可, 📢釋放12港青回港]",0,0,0,0
37,1219940249322713088,"However, #Taiwan didn’t receive invitation to ...",2020-01-22 11:09:55,"[a, journalist, covering, east, asia, and, vp,...",0,1,0,1
42,1219960707971723264,Latest case number estimates for 2019-nCov htt...,2020-01-22 12:31:13,"[health, economist, at, imperial, college, lon...",1,0,0,0

In [10]:
counts = np.array([tweets.academic_count, tweets.journalist_count, tweets.doctor_count, tweets.politician_count]).T
sums = tweets.academic_count + tweets.journalist_count + tweets.doctor_count + tweets.politician_count
proba = counts/sums.values.reshape(-1,1)
tweets['proba'] = proba.tolist()

/Users/maxpaton/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until

In [11]:
tweets

,id,tweet,time,description,academic_count,journalist_count,doctor_count,politician_count,proba
2,1219764042278944768,First Case of Mystery Coronavirus Found In Was...,2020-01-21 23:29:44,"[#, army, #, sfc, #, engineer, #, veteran, 21h...",0,0,0,0,"[nan, nan, nan, nan]"
9,1219844392745422848,Killer Chinese virus has been reported in the ...,2020-01-22 04:49:01,"[i, am, a, realtor, with, agner, &, associate,...",0,0,0,0,"[nan, nan, nan, nan]"
16,1219905081681829888,"Hey, @CDCFlu and other CDC accounts! How come ...",2020-01-22 08:50:10,"[love, .net, ,, software, development, ,, know...",0,0,0,0,"[nan, nan, nan, nan]"
19,1219918349431377921,@realDonaldTrump @Davos First transferred case...,2020-01-22 09:42:54,"[entertainer/food, enthusiast/engaged, housesp...",0,0,0,1,"[0.0, 0.0, 0.0, 1.0]"
21,1219912177089314817,Coronavirus animation awaiting approval. 3 sec...,2020-01-22 09:18:22,"[i, 'm, an, after, effect, ,, cinema4d, and, x...",0,0,0,0,"[nan, nan, nan, nan]"
...,...,...,...,...,...,...,...,...,...
1395206,1256008488494469129,#Coronavirus #Covidhoax #CoronaHoax #Plandemic...,2020-04-30 23:52:13,"[“, believe, those, who, are, seeking, the, tr...",0,0,0,0,"[nan, nan, nan, nan]"
1395211,1256008950832603136,@realDonaldTrump In other news ⁉️Antioch’s Gop...,2020-04-30 23:54:04,"[i, ’, m, here, ., watching/breathing/getting,...",0,0,0,0,"[nan, nan, nan, nan]"
1395214,1256008823422230528,"I be hard as hell to lock down 😂😂 boy, you gon...",2020-04-30 23:53:33,"[happiness, 🥀🤗, -rip, xxxtentacion, ❤️]",0,0,0,0,"[nan, nan, nan, nan]"
1395215,1256008592857206784,24 Hours at the Epicenter of the Coronavirus P...,2020-04-30 23:52:38,"[mainly, data, science, but, also, medium, ,, ...",0,1,0,0,"[0.0, 1.0, 0.0, 0.0]"
1395216,1256008982537269248,President @realDonaldTrump Governor Gavin New...,2020-04-30 23:54:11,"[unconditional, support, of, president, donald...",0,0,0,1,"[0.0, 0.0, 0.0, 1.0]"

In [12]:
# choose label based on max author type count
mask = (pd.notnull(tweets.proba.apply(lambda x: x[0]))) & (tweets.proba.apply(lambda x: x.count(max(x))==1))
valid = tweets[mask]
tweets['label'] = 0
tweets.loc[mask, 'label'] = tweets[['academic_count', 'journalist_count', 'doctor_count', 'politician_count']].idxmax(1)

# encode categorical author type label
# d = {'academic_count': 1, 'journalist_count': 2, 'doctor_count': 3, 'politician_count': 4}
d = {'academic_count': 'academic', 'journalist_count': 'journalist', 'doctor_count': 'doctor', 'politician_count': 'politician'}
tweets['label'] = tweets.label.apply(lambda x: d[x] if x != 0 else x)

In [13]:
tweets.head(5)

,id,tweet,time,description,academic_count,journalist_count,doctor_count,politician_count,proba,label
2,1219764042278944768,First Case of Mystery Coronavirus Found In Was...,2020-01-21 23:29:44,"[#, army, #, sfc, #, engineer, #, veteran, 21h...",0,0,0,0,"[nan, nan, nan, nan]",0
9,1219844392745422848,Killer Chinese virus has been reported in the ...,2020-01-22 04:49:01,"[i, am, a, realtor, with, agner, &, associate,...",0,0,0,0,"[nan, nan, nan, nan]",0
16,1219905081681829888,"Hey, @CDCFlu and other CDC accounts! How come ...",2020-01-22 08:50:10,"[love, .net, ,, software, development, ,, know...",0,0,0,0,"[nan, nan, nan, nan]",0
19,1219918349431377921,@realDonaldTrump @Davos First transferred case...,2020-01-22 09:42:54,"[entertainer/food, enthusiast/engaged, housesp...",0,0,0,1,"[0.0, 0.0, 0.0, 1.0]",politician
21,1219912177089314817,Coronavirus animation awaiting approval. 3 sec...,2020-01-22 09:18:22,"[i, 'm, an, after, effect, ,, cinema4d, and, x...",0,0,0,0,"[nan, nan, nan, nan]",0

In [14]:
len(tweets)

301621

In [15]:
tweets.loc[tweets.label != 0].label.value_counts()

journalist    37408
politician    30622
doctor        10922
academic       8640
Name: label, dtype: int64

## Write dataframe to csv in correct format

In [16]:
tweets = tweets.loc[tweets.label != 0]
tweets = tweets[['label', 'id', 'time', 'tweet']]
tweets.columns = ['screen_name', 'id', 'created_at', 'text']
print(len(tweets))
tweets.to_csv('../tbip/data/covid-tweets-2020/raw/tweets.csv', index=False)

87592

In [ ]:
sentence = 'My name is max. I like food.'
nltk.sentence_tokenize(sentence)

In [1]:
pwd

'/Users/maxpaton/python/ideal_points/data'